### PR TITLE
Add two features and improve documentation

### PR DESCRIPTION
**Pull request by TheJena**
Hi,
I add two features:
- underscores instead of spaces (and some other special characters) in file names
- temporary files during recording

And improved the documentation in the readme

Thank you for the great job you did writing the initial python script!
Bye,
TheJena

### CODE REVIEW

**Comment by Bleuzen** [comment]
Hi,
thanks for your contribution!

Please expect that I will change some things to my liking.

I have a question to your code:
Look at line 379.
Are you sure that this is correct?
```
            if self.process.poll() == None:
                # None means it has no return code (yet), with other words: it is still running

                self.process.kill()

                log.info("[FFmpeg] [" + self.pid + "] killed")
            else:
                if _tmp_file:
...     
```
So the file will only get renamed when FFmpeg not died after the first try (what can happen in some cases)?
Well, that's strange.

**Comment by Bleuzen** [comment]
Here is what I changed:

 - Temporary recording files are now hidden.
I think it's better because so you can use Ctrl+A in your filemanager to select all, but only sucessfull recordings. Not finished recordings will stay hidden.

 - Recordings with the --tmp-file option are now not renamed anymore when the user stops the script

 - Restored default filepattern

 - Renamed "{track}" to "{trackNumber}" again,
because I want to have the same name as the metadata had

 - Changed the categories of your newly added log messages
they shouldn't be infos both

 - Edited README text a little
for example to not use the --debug option by default


I think this is better now for the most users.
I hope you are also ok with it ;)
Again, many thanks for contribution!
(never thought that the first contribution would be that fast and big)

**Comment by TheJena** [comment]
Wonderful!
Do you mind if in the next pull request I also:
- wrap in 80 columns the script
- make more pythonic some pieces of code
?

I am also adding an option to encode the final file in libvorbis-ogg with a given quality.

**Comment by Bleuzen** [comment]
To the code formatting: No. I will try to do it a little better somewhen, but for now you can let it as it is.
I know, some names etc. are not that usual for python, but that's because that is my first real python project and I come from Java ;)

To the reencode thing:
I already thought about it. But dropped the idea, because:
The Spotify listener is not 100% exactly. Sometimes it already triggeres a song change, during the last song still plays. So we don't exactly know, where a song starts, and where it ends.
Thats why I seek to the beginning of the song everytime a recording starts and record a little longer after the song change, so that nothing is missing in the recording of the song before.
So it sometimes happens, that we have some silence at the beginning of the recording, and also a little of the next song at the end of the recording.
I guess nobody wants this. That's why I use Audacity to edit the recordings after recording.
And from Audacity, you can export to whatever you want: ogg, mp3...
So since manual editing is needed anyway, reencoding within the script would make no sense. At least not as long as we don't know how to get the exact time of the song start and end.
Maybe already a note in the README, which recommends the users to use Audacity, would be enough / the best solution.

**Pull request merged**
